### ISSUE TITLE
Error running npm run setup

### ISSUE THREAD

**Issue by bthj** [pavjacko/react-native-vanilla#13]
When running `npm run setup` I get the following:

```
$ npm run setup

> react-native-vanilla@0.8.0 setup .../react-native-vanilla
> node ./utils/setup.js

.../react-native-vanilla/utils/setup.js:315
            });
             ^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

```
$ node --version
v8.12.0

$ npm --version
6.4.1
```
on macOS 10.13.6

**Comment by aurimas535** [comment]
Follow this [PR](https://github.com/pavjacko/react-native-vanilla/pull/12/commits/8d7a88c4ea6845d69b2d93bfbc3b4aef4baabcf2) will be fixed soon
