### ISSUE TITLE
Failed to install on Samsung Tizen

### ISSUE THREAD

**Issue by rdobda-gaia** [pavjacko/react-native-vanilla#16]
Hi, This is a great concept. I've just tried the framework today on Tizen TV, (the latest 5.0 SDK as of this month), when it tries to install on the "web simulator for TV" it just hangs during the install and never completes. I know this framework is evolving very fast so i'm sure it's hard to keep up. I'm really looking for a one-stop solution to develop across multiple TV platforms at the same time and this caught my eye. Thanks! (UPDATE: I previously was unable to install on webOS as well, but after clearing my emulator, this worked just fine!)

**Comment by pavjacko** [comment]
@rdobda-gaia yeah I've experienced lot of issues with latest Tizen Studio (gets worse every release :D). Took 30 minutes to make actual build but it's random. I'll investigate if there is a way how to fix this

**Comment by pavjacko** [comment]
@rdobda-gaia 0.8.2 now supports tizen CLI no need for IDE to be open 🔥 
https://github.com/pavjacko/react-native-vanilla#tizen

**Comment by rdobda-gaia** [comment]
Excellent! I just pulled the latest and followed the steps, and I was able to get it to run on the Samsung 5.0 TV emulator! Great job!

**Comment by rdobda-gaia** [comment]
Hey, so actually, i may not have been doing it correctly, as i am again unable to install. This time, I cleared any old app from my tizen emulator to make sure i have a fresh start, then ran the commands. After the build finished I got this message:

The active profile is used for signing. If you want to sign with other profile, please use '--sign' option.
Author password: An error has occurred. See the log file tizen-sdk/tools/ide/cli.log.
Launching the Tizen application...
--------------------
Platform log view
--------------------
The app with ID: NvVRhWHJST.ReactNativeVanilla is not available for the user 5001
Could not launch the null application.

I am wondering if there is some configuration i need to do for signing. Is this an aspect of configuration that needs to be clearer in this project?

Also, the log file it referred me to says this:
2019-02-14 13:44:09,059 [TRACE] Main.java(130) - Start running Tizen CLI Main class...
2019-02-14 13:44:09,062 [TRACE] Main.java(131) - Argument count:7
2019-02-14 13:44:09,079 [TRACE] BuildWebCLI.java(69) - Execute BuildWebCLI...
2019-02-14 13:44:09,088 [TRACE] BuildWebCLI.java(72) - getRealWorkingPath:/Users/rdobda/Documents/code/react-native-vanilla/platforms/tizen
2019-02-14 13:44:09,925 [TRACE] Main.java(130) - Start running Tizen CLI Main class...
2019-02-14 13:44:09,928 [TRACE] Main.java(131) - Argument count:9
2019-02-14 13:44:09,949 [TRACE] PackageCLI.java(1183) - Execute PackageCLI...
2019-02-14 13:44:09,949 [TRACE] PackageCLI.java(1185) - getRealWorkingPath: /Users/rdobda/Documents/code/react-native-vanilla/platforms/tizen/build
2019-02-14 13:44:10,283 [ERROR] AbstractCLI.java(93) - java.lang.NullPointerException
java.lang.IllegalStateException: java.lang.NullPointerException
	at org.tizen.common.core.command.policy.UncaughtExceptionHandlingPolicy.uncaughtException(UncaughtExceptionHandlingPolicy.java:84)
	at org.tizen.common.core.command.Executor.execute(Executor.java:179)
	at org.tizen.common.core.command.Executor.execute(Executor.java:150)
	at org.tizen.ncli.subcommands.sign.SignCLICommand.getSigningProfile(SignCLICommand.java:139)
	at org.tizen.ncli.subcommands.sign.SignCLICommand.call(SignCLICommand.java:73)
	at org.tizen.ncli.subcommands.sign.SignCLICommand.call(SignCLICommand.java:58)
	at org.tizen.ncli.subcommands.AbstractSubCommand.runCommand(AbstractSubCommand.java:76)
	at org.tizen.ncli.subcommands.packages.PackageCLICommand.call(PackageCLICommand.java:205)
	at org.tizen.ncli.subcommands.packages.PackageCLICommand.call(PackageCLICommand.java:77)
	at org.tizen.ncli.subcommands.AbstractSubCommand.runCommand(AbstractSubCommand.java:76)
	at org.tizen.ncli.ide.shell.PackageCLI.doPackageForWgt(PackageCLI.java:898)
	at org.tizen.ncli.ide.shell.PackageCLI.execute(PackageCLI.java:1258)
	at org.tizen.ncli.ide.shell.AbstractCLI.execute(AbstractCLI.java:91)
	at org.tizen.ncli.ide.shell.Main.run(Main.java:186)
	at org.tizen.ncli.ide.shell.Main.main(Main.java:118)
Caused by: java.lang.NullPointerException
	at org.tizen.ncli.core.ConsolePrompter.password(ConsolePrompter.java:188)
	at org.tizen.ncli.core.ConsolePrompter.batch(ConsolePrompter.java:262)
	at org.tizen.ncli.core.ConsolePrompter.batch(ConsolePrompter.java:223)
	at org.tizen.ncli.core.ConsolePrompter.batch(ConsolePrompter.java:204)
	at org.tizen.common.sign.command.ReadSigningProfileFileCommand.interactForPassword(ReadSigningProfileFileCommand.java:229)
	at org.tizen.common.sign.command.ReadSigningProfileFileCommand.run(ReadSigningProfileFileCommand.java:113)
	at org.tizen.common.core.command.Executor.execute(Executor.java:164)
	... 13 more
2019-02-14 13:44:10,285 [ERROR] Main.java(194) - java.lang.NullPointerException
2019-02-14 13:44:10,773 [TRACE] Main.java(130) - Start running Tizen CLI Main class...
2019-02-14 13:44:10,776 [TRACE] Main.java(131) - Argument count:7
2019-02-14 13:44:10,790 [TRACE] RunCLI.java(56) - Execute RunCLI...

**Comment by rdobda-gaia** [comment]
nevermind. i had to mess around with my certificates. Samsung can be a pain. I got it working again.

**Comment by pavjacko** [comment]
@rdobda-gaia ah great. but more fixes (including missing images and better installation, certs, emulator management) coming soon in `0.9.0`. this one will be major upgrade. should arrive tomorrow!

**Comment by turbidwater** [comment]
If anyone else finds this like I did, the solution I came up with was making a new cert with the Certificate Manager, selecting it as the default in the Certificate Manager and then changing RNVanillaCert in appConfigs/base/renative.json and platformBuilds/{project_name}_tizen.json to the name of my cert. Then I was able to get past this error in the build script.
