### ISSUE TITLE
Installing fails with XCode 10.2

### ISSUE THREAD

**Issue by palavrov** [pavjacko/react-native-vanilla#32]
Just tried to:
`npm install --global --save react-native-vanilla`
and it failed:

```
$ npm install --global --save react-native-vanilla
npm WARN deprecated markdown-to-ast@3.4.0: See https://github.com/textlint/textlint/issues/455
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
/usr/local/bin/rnv -> /usr/local/lib/node_modules/react-native-vanilla/rnv-cli/bin/index.js

> dtrace-provider@0.8.7 install /usr/local/lib/node_modules/react-native-vanilla/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

  ACTION binding_gyp_ndtp_target_build_ndtp .
  TOUCH Release/obj.target/ndtp.stamp

> fsevents@1.2.7 install /usr/local/lib/node_modules/react-native-vanilla/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/usr/local/lib/node_modules/react-native-vanilla/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node" is installed via remote

> husky@1.2.0 install /usr/local/lib/node_modules/react-native-vanilla/node_modules/husky
> node husky install

husky > setting up git hooks
Can't find .git, skipping Git hooks installation.
Please check that you're in a cloned repository or run 'git init' to create an empty Git repository and reinstall husky.

> detox@9.0.4 postinstall /usr/local/lib/node_modules/react-native-vanilla/node_modules/detox
> node scripts/postinstall.js

+ xcodebuild -version
+++ dirname /usr/local/lib/node_modules/react-native-vanilla/node_modules/detox/scripts/build_framework.ios.sh
++ dirname /usr/local/lib/node_modules/react-native-vanilla/node_modules/detox/scripts
+ detoxRootPath=/usr/local/lib/node_modules/react-native-vanilla/node_modules/detox
++ node -p 'require('\''/usr/local/lib/node_modules/react-native-vanilla/node_modules/detox/package.json'\'').version'
+ detoxVersion=9.0.4
++ echo 9.0.4
++ xcodebuild -version
++ shasum
++ awk '{print $1}'
+ sha1=7185509d4aeaa6fe07e3a067f58f475b7d34323e
+ detoxFrameworkDirPath=/Users/palavrov/Library/Detox/ios/7185509d4aeaa6fe07e3a067f58f475b7d34323e
+ detoxFrameworkPath=/Users/palavrov/Library/Detox/ios/7185509d4aeaa6fe07e3a067f58f475b7d34323e/Detox.framework
+ main
+ '[' -d /Users/palavrov/Library/Detox/ios/7185509d4aeaa6fe07e3a067f58f475b7d34323e ']'
+ '[' '!' -d /Users/palavrov/Library/Detox/ios/7185509d4aeaa6fe07e3a067f58f475b7d34323e/Detox.framework ']'
+ echo '/Users/palavrov/Library/Detox/ios/7185509d4aeaa6fe07e3a067f58f475b7d34323e was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Users/palavrov/Library/Detox/ios/7185509d4aeaa6fe07e3a067f58f475b7d34323e and trying to rebuild.'
/Users/palavrov/Library/Detox/ios/7185509d4aeaa6fe07e3a067f58f475b7d34323e was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Users/palavrov/Library/Detox/ios/7185509d4aeaa6fe07e3a067f58f475b7d34323e and trying to rebuild.
+ rm -rf /Users/palavrov/Library/Detox/ios/7185509d4aeaa6fe07e3a067f58f475b7d34323e
+ prepareAndBuildFramework
+ '[' -d /usr/local/lib/node_modules/react-native-vanilla/node_modules/detox/ios ']'
+ detoxSourcePath=/usr/local/lib/node_modules/react-native-vanilla/node_modules/detox/ios_src
+ extractSources /usr/local/lib/node_modules/react-native-vanilla/node_modules/detox/ios_src
+ detoxSourcePath=/usr/local/lib/node_modules/react-native-vanilla/node_modules/detox/ios_src
+ echo 'Extracting Detox sources...'
Extracting Detox sources...
+ mkdir -p /usr/local/lib/node_modules/react-native-vanilla/node_modules/detox/ios_src
+ tar -xjf /usr/local/lib/node_modules/react-native-vanilla/node_modules/detox/Detox-ios-src.tbz -C /usr/local/lib/node_modules/react-native-vanilla/node_modules/detox/ios_src
+ buildFramework /usr/local/lib/node_modules/react-native-vanilla/node_modules/detox/ios_src
+ detoxSourcePath=/usr/local/lib/node_modules/react-native-vanilla/node_modules/detox/ios_src
+ echo 'Building Detox.framework from /usr/local/lib/node_modules/react-native-vanilla/node_modules/detox/ios_src...'
Building Detox.framework from /usr/local/lib/node_modules/react-native-vanilla/node_modules/detox/ios_src...
+ mkdir -p /Users/palavrov/Library/Detox/ios/7185509d4aeaa6fe07e3a067f58f475b7d34323e
+ /usr/local/lib/node_modules/react-native-vanilla/node_modules/detox/scripts/build_universal_framework.sh /usr/local/lib/node_modules/react-native-vanilla/node_modules/detox/ios_src/Detox.xcodeproj /Users/palavrov/Library/Detox/ios/7185509d4aeaa6fe07e3a067f58f475b7d34323e
child_process.js:658
    throw err;
    ^

Error: Command failed: /usr/local/lib/node_modules/react-native-vanilla/node_modules/detox/scripts/build_framework.ios.sh
    at checkExecSyncError (child_process.js:637:11)
    at Object.execFileSync (child_process.js:655:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-vanilla/node_modules/detox/scripts/postinstall.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11
npm WARN react-native@0.58.5 requires a peer of react@16.6.3 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-web@0.9.9 requires a peer of react-art@>=16.5.1 but none is installed. You must install peer dependencies yourself.
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@13.1.0 requires a peer of eslint-plugin-import@^2.14.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! detox@9.0.4 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the detox@9.0.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/palavrov/.npm/_logs/2019-03-27T19_33_41_650Z-debug.log
```

Detox is using old swift syntax that the new XCode 10.2 doesn't support and fails to build.
Workaround is to install XCode 10.1 and switch to its command tools:
[Working with Multiple Versions of Xcode](https://medium.com/@hacknicity/working-with-multiple-versions-of-xcode-e331c01aa6bc)
Another possible solution is to update Detox to newer version, may be the issue is already fixed. (latest is 12.1.1 and here the version is 9.0.4)

**Comment by pavjacko** [comment]
@palavrov thanks for the tip! I experienced few other issues with Xcode 10.2 + RN 0.58.5 as well. will investigate soon!

**Comment by pavjacko** [comment]
@palavrov as of `0.19.4` this should be fixed now
